name: whatsapp_share_example
description: Demonstrates how to use the whatsapp_share plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  screenshot: ^1.0.0-nullsafety.1
#  documents_picker: ^1.0.0
  path_provider: ^2.0.2
  image_picker: ^0.7.5+3


  whatsapp_share:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
